name: macOS CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Install LSP servers needed for tests
        run: |
          brew install llvm python-lsp-server ruff ty cargo-nextest
          # It seems like TypeScript 7 cannot be found by the typescript-language-server, so we pin an older version.
          npm install -g typescript-language-server typescript@6

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-analyzer

      - name: Check formatting
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build release binary
        run: cargo build --release

      - name: Run tests
        run: cargo nextest run --profile ci -- --include-ignored

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
